apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  # The URL references the MongoDB service name defined above: mongodb-service
  MONGO_URL: "mongodb://mongodb-service:27017/bookstoredb"
